### ISSUE TITLE
Codepen demo

### ISSUE THREAD

**Issue by anthonybrown** [theuprising/react-gsap-parallax#1]
Your codepen demo doesn't work

**Comment by amonks** [comment]
You're right! I'll look into it and get back to you.

**Comment by amonks** [comment]
the non-codepen demo does work: https://react-gsap-parallax.now.sh/#

**Comment by amonks** [comment]
...but not with recent versions, still debugging

**Comment by amonks** [comment]
I hadn't updated the examples or readme since version 2. Embarrassing! Now fixed.

Thanks a ton for finding this :)

the big change is that rather than scrollDistance, the container takes height and top props. The upside is that you can position other (non-parallaxed) elements above or below it.

**Comment by anthonybrown** [comment]
appreciate the fix!

🚀

**Comment by amonks** [comment]
:)

I know the readme's pretty scant, so I'm happy to take usage questions here, too. Let me know if you run into any snags.
