### ISSUE TITLE
Warning: Failed prop type: The prop `registerParallaxElement` is marked as required in `ParallaxElement`, but its value is `undefined`.

### ISSUE THREAD

**Issue by jdobrowner** [theuprising/react-gsap-parallax#2]
Warning: Failed prop type: The prop `registerParallaxElement` is marked as required in `ParallaxElement`, but its value is `undefined`.

I am getting this warning after I put this in render:

<ParallaxContainer height={10000} top={0} scrolljack={false} onScroll={x => x}>
      <Parallax style={{top: "0"}} keyframes={
            {
                 "0%": { left: 0, easeIn: Linear.ease },
                "10%": { left: "-50%", easeOut: Linear.ease }
            }}>
      </Parallax>
</ParallaxContainer>

**Comment by amonks** [comment]
Good catch! Thanks a ton for reporting this!

The warning was a false-positive, but I've fixed how it's handled in v2.2.2.

Also: 

your example code made me realize that _my_ example code around easing was incorrect.: TimelineLite.to takes a single `ease` property, not easeIn and easeOut. I've updated the examples accordingly.

Please report back if you have any questions / issues :)

**Comment by jdobrowner** [comment]
Thanks, the warning is gone, but I also found that react-gsap-parallax was causing this one: 

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Great tool by the way!

**Comment by amonks** [comment]
Thanks for the PropTypes deprecation callout!

I committed a fix, and it'll go out in the next version bump. :D 


Glad you like the library!
